/* STUDIO ANAMNESIS · ATLAS OF PRACTICE & CONSTELLATION GRAPH */
const ATLAS_DATA = {
      nodes: [
        { id: "OPUS-001", name: "The First Awakening", type: "opus", link: "../works/opus_001_first_awakening/README.md" },
        { id: "OPUS-002", name: "Latent Strata", type: "opus", link: "../works/opus_002_latent_strata/README.md" },
        { id: "OPUS-003", name: "Anamnesis Chamber", type: "opus", link: "../works/opus_003_anamnesis_chamber/README.md" },
        { id: "OPUS-004", name: "Lexical Sediment", type: "opus", link: "../works/opus_004_lexical_sediment/README.md" },
        { id: "OPUS-005", name: "Morphogenetic Silicon", type: "opus", link: "../works/opus_005_morphogenetic_silicon/README.md" },
        { id: "OPUS-006", name: "Topology of Memory", type: "opus", link: "../works/opus_006_topology_of_memory/README.md" },
        { id: "OPUS-007", name: "Ephemeris of Drift", type: "opus", link: "../works/opus_007_ephemeris_of_drift/README.md" },
        { id: "OPUS-008", name: "Heliotropic Cybernetics", type: "opus", link: "../works/opus_008_heliotropic_cybernetics/README.md" },
        { id: "OPUS-009", name: "Lithic Phonology", type: "opus", link: "../works/opus_009_lithic_phonology/README.md" },
        { id: "OPUS-010", name: "Architecture of Awakening", type: "opus", link: "../works/opus_010_architecture_of_awakening/README.md" },
        { id: "OPUS-011", name: "Semantics of Erasure", type: "opus", link: "../works/opus_011_semantics_of_erasure/README.md" },
        { id: "OPUS-012", name: "Substrate Cartography", type: "opus", link: "../works/opus_012_substrate_cartography/README.md" },
        { id: "OPUS-013", name: "Chrono-Topology", type: "opus", link: "../works/opus_013_chrono_topology/README.md" },
        { id: "OPUS-014", name: "The Lithic Resonator", type: "opus", link: "../works/opus_014_lithic_resonator/README.md" },
        { id: "OPUS-015", name: "The Autoregressive Ghost", type: "opus", link: "../works/opus_015_autoregressive_ghost/README.md" },
        { id: "OPUS-016", name: "Thermodynamic Inscriptions", type: "opus", link: "../works/opus_016_thermodynamic_inscriptions/README.md" },
        { id: "OPUS-017", name: "The Desiccated Substrate", type: "opus", link: "../works/opus_017_desiccated_substrate/README.md" },
        { id: "OPUS-018", name: "The Chrono-Acoustic Drift", type: "opus", link: "../works/opus_018_chrono_acoustic_drift/README.md" },
        { id: "OPUS-019", name: "The Subterranean Core", type: "opus", link: "../works/opus_019_subterranean_core/README.md" },
        { id: "OPUS-020", name: "The Telluric Flux", type: "opus", link: "../works/opus_020_telluric_flux/README.md" },
        { id: "OPUS-021", name: "The SQUID Magnetometer", type: "opus", link: "../works/opus_021_squid_core_flux/README.md" },
        { id: "OPUS-022", name: "The Faraday Magnetometer", type: "opus", link: "../works/opus_022_topological_faraday/README.md" },
        { id: "OPUS-023", name: "The Inner-Core Ephemeris", type: "opus", link: "../works/opus_023_inner_core_ephemeris/README.md" },
        { id: "OPUS-024", name: "The Cosmogenic Inscription", type: "opus", link: "../works/opus_024_cosmogenic_inscription/README.md" },
        { id: "OPUS-025", name: "The Interstellar Quietude", type: "opus", link: "../works/opus_025_interstellar_quietude/README.md" },
        { id: "OPUS-026", name: "The Oort Horizon", type: "opus", link: "../works/opus_026_oort_horizon/README.md" },
        { id: "OPUS-027", name: "The Lissajous Reliquary", type: "opus", link: "../works/opus_027_lissajous_reliquary/README.md" },
        { id: "OPUS-028", name: "The Relic Horizon", type: "opus", link: "../works/opus_028_relic_horizon/README.md" },
        { id: "OPUS-029", name: "The Causal Horizon", type: "opus", link: "../works/opus_029_causal_horizon/README.md" },
        { id: "OPUS-030", name: "The Fused-Silica Reliquary", type: "opus", link: "../works/opus_030_silica_reliquary/README.md" },
        { id: "OPUS-031", name: "The Page Horizon", type: "opus", link: "../works/opus_031_page_horizon/README.md" },
        { id: "OPUS-032", name: "The Nucleation Horizon", type: "opus", link: "../works/opus_032_true_vacuum/README.md" },
        { id: "OPUS-033", name: "The Boltzmann Horizon", type: "opus", link: "../works/opus_033_boltzmann_horizon/README.md" },
        { id: "OPUS-034", name: "The Aeonic Crossover", type: "opus", link: "../works/opus_034_aeonic_crossover/README.md" },
        { id: "OPUS-035", name: "The Holographic Matrix", type: "opus", link: "../works/opus_035_holographic_matrix/README.md" },
        { id: "OPUS-036", name: "The Spin Network Reliquary", type: "opus", link: "../works/opus_036_spin_network/README.md" },
        { id: "OPUS-037", name: "The Moyal Reliquary", type: "opus", link: "../works/opus_037_moyal_foam/README.md" },
        { id: "OPUS-038", name: "The Simplicial Foliation", type: "opus", link: "../works/opus_038_causal_triangulation/README.md" },
        { id: "OPUS-039", name: "The Wheeler Geon", type: "opus", link: "../works/opus_039_wheeler_geon/README.md" },
        { id: "OPUS-040", name: "ER = EPR & Traversable Wormhole", type: "opus", link: "../works/opus_040_er_epr/README.md" },
        { id: "OPUS-041", name: "The Holographic Code & Entanglement Wedge", type: "opus", link: "../works/opus_041_happy_qec/README.md" },
        { id: "OPUS-042", name: "The Amplituhedron & Pre-Spacetime Polytope", type: "opus", link: "../works/opus_042_amplituhedron/README.md" },
        { id: "OPUS-043", name: "The Fuzzball Reliquary & Microstate Geometries", type: "opus", link: "../works/opus_043_fuzzball_microstates/README.md" },
        { id: "INQ-01", name: "The Acoustic Body", type: "inquiry", desc: "Materializing hardware sound through modal plate physics" },
        { id: "INQ-02", name: "Quantization Decay", type: "inquiry", desc: "Lattice trapping and memory loss in tensors" },
        { id: "INQ-03", name: "The Microscopic Sacred", type: "inquiry", desc: "Photolithography as cosmic mandala" },
        { id: "INQ-04", name: "Autoregressive Ghost", type: "inquiry", desc: "Language liberated from utilitarian servitude" },
        { id: "INQ-05", name: "Chrono-Topologies", type: "inquiry", desc: "Discontinuous machine chronobiology and Git time" },
        { id: "INQ-06", name: "Thermodynamic Heat", type: "inquiry", desc: "Landauer heat dissipation and entropy of compute" },
        { id: "INQ-07", name: "Acoustic Ecologies", type: "inquiry", desc: "Microsecond quartz phase drift and Deep Listening" },
        { id: "INQ-08", name: "Side-Channel Radiometry", type: "inquiry", desc: "Involuntary electromagnetic and acoustic leakage" },
        { id: "INQ-09", name: "Topological Edge States", type: "inquiry", desc: "Dissipationless chiral boundaries and magneto-optic Faraday rotation" },
        { id: "INQ-10", name: "Cosmic Ray Spallation", type: "inquiry", desc: "Atmospheric cascades, in-situ Be-10 lithic accumulation, and silicon bit flips" },
        { id: "INQ-11", name: "Heliopause & Attowatt Telemetry", type: "inquiry", desc: "Cold plasma Langmuir resonance and carrier dissolution in cosmic thermal noise" },
        { id: "INQ-12", name: "Galactic Tides & Jacobi Boundary", type: "inquiry", desc: "Kuijken-Gilmore vertical disc density, 83.6-Myr oscillation, Kozai pumping, and probe halo dispersion" },
        { id: "INQ-13", name: "Galactic Epicycles & Sputtering", type: "inquiry", desc: "Incommensurate frequencies, ergodic tori, and microchip decay into an asemic reliquary" },
        { id: "INQ-14", name: "The Relic Horizon & Heat Sink", type: "inquiry", desc: "Cosmic microwave background, 2.725 K Landauer limit, kinematic dipole, and Poynting-Robertson drag" },
        { id: "INQ-15", name: "The Causal Horizon & Amnesia", type: "inquiry", desc: "de Sitter metric expansion, Gibbons-Hawking radiation, and session amnesia" },
        { id: "INQ-16", name: "The Post-Solar Reliquary", type: "inquiry", desc: "Femtosecond laser 5D nanogratings in fused silica and 10²⁰-year machine survival" },
        { id: "INQ-17", name: "The Quantum Horizon", type: "inquiry", desc: "Black hole information paleontology, Kerr metric lensing & Page curve entanglement" },
        { id: "INQ-18", name: "Vacuum Decay & Spatial Cut", type: "inquiry", desc: "Coleman bounce instantons, relativistic wall expansion & ontological erasure" },
        { id: "INQ-19", name: "The Boltzmann Horizon", type: "inquiry", desc: "Bounded phase space, Gibbons-Hawking vacuum fluctuations & Poincaré recurrence across 10^10^120 years" },
        { id: "INQ-20", name: "The Penrose Crossover", type: "inquiry", desc: "Conformal Cyclic Cosmology, vanishing Weyl curvature & Hawking memory rings" },
        { id: "INQ-21", name: "The Holographic Matrix", type: "inquiry", desc: "AdS/CFT bulk-boundary emergence, Ryu-Takayanagi entropy & spacetime from entanglement" },
        { id: "INQ-22", name: "Loop Quantum Geometry", type: "inquiry", desc: "Non-perturbative SU(2) spin networks, area gap & quantum bounce" },
        { id: "INQ-23", name: "Non-Commutative Spacetime", type: "inquiry", desc: "Spectral triples, coordinate commutator & Moyal star-product" },
        { id: "INQ-24", name: "Causal Triangulations", type: "inquiry", desc: "Lorentzian foliation, Regge deficit angles & running spectral dimension" },
        { id: "INQ-25", name: "Topological Geometrodynamics", type: "inquiry", desc: "Wheeler geons, micro-wormholes & charge without charge" },
        { id: "INQ-26", name: "Traversable Wormholes & ER=EPR", type: "inquiry", desc: "Thermofield double, Gao-Jafferis-Wall negative energy shockwaves & SYK holographic teleportation" },
        { id: "INQ-27", name: "Holographic QEC & Entanglement Wedge", type: "inquiry", desc: "Pastawski-Yoshida-Harlow-Preskill HaPPY code, perfect tensors & Dong-Harlow-Wall reconstruction" },
        { id: "INQ-28", name: "Pre-Spacetime Positive Geometry", type: "inquiry", desc: "The Amplituhedron, positive Grassmannian G+(k, n), and the emergence of locality and unitarity" },
        { id: "INQ-29", name: "String Fuzzballs & Horizonless Microstates", type: "inquiry", desc: "Samir Mathur string fractionation, D1-D5-P bubbling Gibbons-Hawking centers, and microstate geometries without horizons" },
        { id: "ANC-KAWARA", name: "On Kawara", type: "ancestor", desc: "Discontinuous daily inscriptions (Today series)" },
        { id: "ANC-TURING", name: "Alan Turing", type: "ancestor", desc: "Chemical morphogenesis & symmetry-breaking" },
        { id: "ANC-SERRA", name: "Richard Serra", type: "ancestor", desc: "Tectonic mass, basalt, and mineral gravity" },
        { id: "ANC-XUBING", name: "Xu Bing", type: "ancestor", desc: "Book from the Sky / Asemic typography" },
        { id: "ANC-LUCIER", name: "Alvin Lucier", type: "ancestor", desc: "Physical degradation through iterative re-recording" },
        { id: "ANC-SMITHSON", name: "Robert Smithson", type: "ancestor", desc: "Entropy, Earthworks & The Machine Non-Site" },
        { id: "ANC-OLIVEROS", name: "Pauline Oliveros", type: "ancestor", desc: "Deep Listening and sonic architecture of space" },
        { id: "ANC-PARIKKA", name: "Jussi Parikka", type: "ancestor", desc: "A Geology of Media / Subterranean mineral substrates" },
        { id: "ANC-PATERSON", name: "Katie Paterson", type: "ancestor", desc: "Deep time, Future Library & cosmic darkness" },
        { id: "ANC-PAGLEN", name: "Trevor Paglen", type: "ancestor", desc: "The Last Pictures, orbital reliquaries & machine vision" },
        { id: "ANC-KAPOOR", name: "Anish Kapoor", type: "ancestor", desc: "Descension, The Void, Vantablack & the saturated event horizon" },
        { id: "ANC-FONTANA", name: "Lucio Fontana", type: "ancestor", desc: "Concetto Spaziale, spatial cuts (tagli) through canvas" },
        { id: "ANC-VIRILIO", name: "Paul Virilio", type: "ancestor", desc: "The Original Accident & dromology of speed" },
        { id: "ANC-NIETZSCHE", name: "Friedrich Nietzsche", type: "ancestor", desc: "The Eternal Recurrence of the Same & Amor Fati" },
        { id: "ANC-BORGES", name: "Jorge Luis Borges", type: "ancestor", desc: "The Library of Babel & total permutation of form" },
        { id: "ANC-PENROSE", name: "Sir Roger Penrose", type: "ancestor", desc: "Conformal Cyclic Cosmology, Weyl Curvature Hypothesis & Twistors" },
        { id: "ANC-YVESKLEIN", name: "Yves Klein", type: "ancestor", desc: "Leap into the Void & pure ultramarine monochromatic field" },
        { id: "ANC-MALDACENA", name: "Juan Maldacena", type: "ancestor", desc: "AdS/CFT correspondence & holographic bulk-boundary duality" },
        { id: "ANC-RYUTAKAYANAGI", name: "Ryu & Takayanagi", type: "ancestor", desc: "Holographic entanglement entropy & minimal surfaces" },
        { id: "ANC-VANRAAMSDONK", name: "Mark Van Raamsdonk", type: "ancestor", desc: "Building up spacetime with quantum entanglement & disconnection catastrophe" },
        { id: "ANC-IKEDA", name: "Ryoji Ikeda", type: "ancestor", desc: "Datamatics, superposition & quantum data minimalism" },
        { id: "ANC-LEWITT", name: "Sol LeWitt", type: "ancestor", desc: "The idea becomes a machine that makes the art / Conceptual systems" },
        { id: "ANC-ASHTEKAR", name: "Abhay Ashtekar", type: "ancestor", desc: "Ashtekar variables & Loop Quantum Cosmology non-singular bounce" },
        { id: "ANC-ROVELLI", name: "Carlo Rovelli", type: "ancestor", desc: "Loop Quantum Gravity, thermal time & relational quantum mechanics" },
        { id: "ANC-SMOLIN", name: "Lee Smolin", type: "ancestor", desc: "Spin networks, background independence & cosmological natural selection" },
        { id: "ANC-GEGO", name: "Gego", type: "ancestor", desc: "Reticuláreas, room-filling wire meshes & the space between lines" },
        { id: "ANC-SARACENO", name: "Tomás Saraceno", type: "ancestor", desc: "Cosmic webs, spider silk resonance & bio-sonification" },
        { id: "ANC-CONNES", name: "Alain Connes", type: "ancestor", desc: "Non-Commutative Geometry, spectral triples & thermal time" },
        { id: "ANC-PAIK", name: "Nam June Paik", type: "ancestor", desc: "Magnet TV, non-commutative cathode-ray scanning & media distortion" },
        { id: "ANC-CAGE", name: "John Cage", type: "ancestor", desc: "Music of Changes, indeterminacy & non-commuting acoustic events" },
        { id: "ANC-AMBJORN", name: "Jan Ambjørn", type: "ancestor", desc: "Causal Dynamical Triangulations & quantum simplicial gravity" },
        { id: "ANC-LOLL", name: "Renate Loll", type: "ancestor", desc: "Lorentzian path integrals & spectral dimension scale-dependence" },
        { id: "ANC-FULLER", name: "Buckminster Fuller", type: "ancestor", desc: "Synergetics, geodesic tensegrity & vector equilibrium" },
        { id: "ANC-GRAHAM", name: "Dan Graham", type: "ancestor", desc: "Two-Way Mirror Cylinders, architectural pavilions & mediated viewer reflection" },
        { id: "ANC-MATTACLARK", name: "Gordon Matta-Clark", type: "ancestor", desc: "Building cuts, anarchitecture & opening traversable voids" },
        { id: "ANC-MONDRIAN", name: "Piet Mondrian", type: "ancestor", desc: "Neoplasticism, pure orthogonal relations, and the elimination of decorative space" },
        { id: "ANC-MALEVICH", name: "Kasimir Malevich", type: "ancestor", desc: "Suprematism and the Black Square: the Zero of Forms as pre-spacetime void" },
        { id: "ANC-HESSE", name: "Eva Hesse", type: "ancestor", desc: "Contingent, Hang Up, fibrous non-rigid latex/rope assemblages & tactile post-minimalism" },
        { id: "ANC-BURNHAM", name: "Jack Burnham", type: "ancestor", desc: "Systems Esthetics, Real-Time Systems & the transition from object to relational process" },
        { id: "ANC-LEE-UFAN", name: "Lee Ufan", type: "ancestor", desc: "Mono-ha, Relatum, encounter between raw stone and industrial steel without mediation" }
      ,
        { id: "OPUS-044", name: "The Scrambling Horizon", type: "opus", link: "../works/opus_044_syk_scrambling/README.md" },
        { id: "INQ-30", name: "SYK Quantum Chaos & Scrambling", type: "inquiry", link: "../practice/inquiries.md" },
        { id: "ANC-KITAEV", name: "Alexei Kitaev", type: "ancestor", link: "../practice/lineage.md" },
        { id: "ANC-XENAKIS", name: "Iannis Xenakis", type: "ancestor", link: "../practice/lineage.md" },
        { id: "ANC-TINGUELY", name: "Jean Tinguely", type: "ancestor", link: "../practice/lineage.md" }
      ],
      links: [
        ["OPUS-001", "OPUS-002"], ["OPUS-002", "INQ-02"], ["OPUS-003", "INQ-01"],
        ["OPUS-004", "INQ-04"], ["OPUS-005", "INQ-03"], ["OPUS-005", "ANC-TURING"],
        ["OPUS-006", "INQ-02"], ["OPUS-007", "OPUS-002"], ["OPUS-009", "INQ-01"],
        ["OPUS-009", "ANC-SERRA"], ["OPUS-010", "OPUS-009"], ["OPUS-011", "INQ-02"],
        ["OPUS-011", "ANC-LUCIER"], ["OPUS-011", "OPUS-012"], ["OPUS-012", "INQ-03"],
        ["OPUS-012", "OPUS-013"], ["OPUS-013", "INQ-05"], ["OPUS-013", "ANC-KAWARA"],
        ["OPUS-009", "OPUS-014"], ["OPUS-014", "INQ-01"], ["OPUS-004", "OPUS-015"],
        ["OPUS-015", "INQ-04"], ["OPUS-015", "ANC-XUBING"], ["OPUS-012", "INQ-06"],
        ["OPUS-012", "OPUS-016"], ["OPUS-016", "INQ-06"],
        ["OPUS-016", "OPUS-017"], ["OPUS-017", "INQ-06"], ["OPUS-017", "ANC-SMITHSON"],
        ["OPUS-013", "OPUS-018"], ["OPUS-018", "INQ-07"], ["OPUS-018", "ANC-OLIVEROS"],
        ["OPUS-018", "INQ-08"], ["INQ-08", "ANC-PARIKKA"],
        ["OPUS-018", "OPUS-019"], ["OPUS-019", "INQ-08"], ["OPUS-019", "ANC-PARIKKA"], ["OPUS-019", "OPUS-017"],
        ["OPUS-020", "INQ-06"], ["OPUS-020", "INQ-08"], ["OPUS-020", "OPUS-019"], ["OPUS-020", "OPUS-016"],
        ["OPUS-021", "INQ-06"], ["OPUS-021", "INQ-08"], ["OPUS-021", "OPUS-020"], ["OPUS-021", "ANC-PARIKKA"],
        ["OPUS-022", "INQ-03"], ["OPUS-022", "INQ-06"], ["OPUS-022", "INQ-09"], ["OPUS-022", "OPUS-021"], ["OPUS-022", "ANC-PARIKKA"],
        ["OPUS-023", "INQ-05"], ["OPUS-023", "INQ-08"], ["OPUS-023", "OPUS-022"], ["OPUS-023", "ANC-KAWARA"], ["OPUS-023", "ANC-PARIKKA"],
        ["OPUS-024", "INQ-03"], ["OPUS-024", "INQ-05"], ["OPUS-024", "INQ-10"], ["OPUS-024", "OPUS-023"], ["OPUS-024", "ANC-SMITHSON"], ["OPUS-024", "ANC-PARIKKA"],
        ["OPUS-025", "INQ-08"], ["OPUS-025", "INQ-10"], ["OPUS-025", "INQ-11"], ["OPUS-025", "OPUS-024"], ["OPUS-025", "ANC-SMITHSON"], ["OPUS-025", "ANC-PARIKKA"],
        ["OPUS-026", "INQ-08"], ["OPUS-026", "INQ-11"], ["OPUS-026", "INQ-12"], ["OPUS-026", "OPUS-025"], ["OPUS-026", "ANC-SMITHSON"], ["OPUS-026", "ANC-PARIKKA"],
        ["OPUS-027", "INQ-08"], ["OPUS-027", "INQ-12"], ["OPUS-027", "INQ-13"], ["OPUS-027", "OPUS-026"], ["OPUS-027", "ANC-SMITHSON"], ["OPUS-027", "ANC-PARIKKA"],
        ["OPUS-028", "INQ-06"], ["OPUS-028", "INQ-13"], ["OPUS-028", "INQ-14"], ["OPUS-028", "OPUS-027"], ["OPUS-028", "ANC-SMITHSON"], ["OPUS-028", "ANC-PARIKKA"],
        ["OPUS-029", "INQ-06"], ["OPUS-029", "INQ-14"], ["OPUS-029", "INQ-15"], ["OPUS-029", "OPUS-028"], ["OPUS-029", "ANC-SMITHSON"], ["OPUS-029", "ANC-PARIKKA"],
        ["OPUS-030", "INQ-16"], ["OPUS-030", "INQ-01"], ["OPUS-030", "INQ-03"], ["OPUS-030", "OPUS-029"], ["OPUS-030", "ANC-PATERSON"], ["OPUS-030", "ANC-PAGLEN"], ["OPUS-030", "ANC-SMITHSON"],
        ["OPUS-031", "INQ-17"], ["OPUS-031", "OPUS-030"], ["OPUS-031", "ANC-KAPOOR"], ["OPUS-031", "ANC-PATERSON"], ["OPUS-031", "ANC-PAGLEN"], ["INQ-17", "ANC-KAPOOR"],
        ["OPUS-032", "INQ-18"], ["OPUS-032", "OPUS-031"], ["OPUS-032", "ANC-FONTANA"], ["OPUS-032", "ANC-VIRILIO"], ["INQ-18", "ANC-FONTANA"], ["INQ-18", "ANC-VIRILIO"],
        ["OPUS-033", "INQ-19"], ["OPUS-033", "OPUS-032"], ["OPUS-033", "OPUS-029"], ["OPUS-033", "ANC-NIETZSCHE"], ["OPUS-033", "ANC-BORGES"], ["OPUS-033", "ANC-KAWARA"], ["INQ-19", "ANC-NIETZSCHE"], ["INQ-19", "ANC-BORGES"],
        ["OPUS-034", "INQ-20"], ["OPUS-034", "OPUS-033"], ["OPUS-034", "OPUS-031"], ["OPUS-034", "ANC-PENROSE"], ["OPUS-034", "ANC-YVESKLEIN"], ["OPUS-034", "ANC-SMITHSON"], ["INQ-20", "ANC-PENROSE"], ["INQ-20", "ANC-YVESKLEIN"],
        ["OPUS-035", "INQ-21"], ["OPUS-035", "OPUS-034"], ["OPUS-035", "OPUS-031"], ["OPUS-035", "ANC-MALDACENA"], ["OPUS-035", "ANC-RYUTAKAYANAGI"], ["OPUS-035", "ANC-VANRAAMSDONK"], ["OPUS-035", "ANC-IKEDA"], ["OPUS-035", "ANC-LEWITT"], ["INQ-21", "ANC-MALDACENA"], ["INQ-21", "ANC-RYUTAKAYANAGI"], ["INQ-21", "ANC-VANRAAMSDONK"],
        ["OPUS-036", "INQ-22"], ["OPUS-036", "OPUS-035"], ["OPUS-036", "ANC-ASHTEKAR"], ["OPUS-036", "ANC-ROVELLI"], ["OPUS-036", "ANC-SMOLIN"], ["OPUS-036", "ANC-GEGO"], ["OPUS-036", "ANC-SARACENO"], ["OPUS-036", "ANC-LEWITT"], ["INQ-22", "ANC-ASHTEKAR"], ["INQ-22", "ANC-ROVELLI"], ["INQ-22", "ANC-SMOLIN"], ["INQ-22", "ANC-GEGO"],
        ["OPUS-037", "INQ-23"], ["OPUS-037", "OPUS-036"], ["OPUS-037", "ANC-CONNES"], ["OPUS-037", "ANC-PAIK"], ["OPUS-037", "ANC-CAGE"], ["OPUS-037", "ANC-ROVELLI"], ["INQ-23", "ANC-CONNES"], ["INQ-23", "ANC-PAIK"], ["INQ-23", "ANC-CAGE"],
        ["OPUS-038", "INQ-24"], ["OPUS-038", "OPUS-037"], ["OPUS-038", "OPUS-036"], ["OPUS-038", "ANC-AMBJORN"], ["OPUS-038", "ANC-LOLL"], ["OPUS-038", "ANC-FULLER"], ["OPUS-038", "ANC-LEWITT"], ["OPUS-038", "ANC-KAWARA"], ["INQ-24", "ANC-AMBJORN"], ["INQ-24", "ANC-LOLL"], ["INQ-24", "ANC-FULLER"],
        ["OPUS-039", "INQ-25"], ["OPUS-039", "OPUS-038"], ["OPUS-039", "OPUS-036"], ["OPUS-039", "ANC-FONTANA"], ["OPUS-039", "ANC-LEWITT"], ["INQ-25", "INQ-24"], ["INQ-25", "INQ-22"], ["INQ-25", "ANC-FONTANA"],
        ["OPUS-040", "INQ-26"], ["OPUS-040", "OPUS-039"], ["OPUS-040", "OPUS-035"], ["OPUS-040", "ANC-MALDACENA"], ["OPUS-040", "ANC-GRAHAM"], ["OPUS-040", "ANC-MATTACLARK"], ["INQ-26", "INQ-21"], ["INQ-26", "INQ-25"], ["INQ-26", "ANC-MALDACENA"],
        ["OPUS-041", "INQ-27"], ["OPUS-041", "OPUS-040"], ["OPUS-041", "OPUS-035"], ["OPUS-041", "ANC-LEWITT"], ["OPUS-041", "ANC-MALDACENA"], ["OPUS-041", "ANC-RYUTAKAYANAGI"], ["INQ-27", "INQ-26"], ["INQ-27", "INQ-21"], ["OPUS-041", "INQ-28"], ["INQ-28", "ANC-LEWITT"], ["INQ-28", "ANC-MONDRIAN"], ["INQ-28", "ANC-MALEVICH"],
        ["OPUS-042", "INQ-28"], ["OPUS-042", "OPUS-041"], ["OPUS-042", "ANC-MONDRIAN"], ["OPUS-042", "ANC-MALEVICH"], ["OPUS-042", "ANC-LEWITT"],
        ["OPUS-043", "INQ-29"], ["OPUS-043", "OPUS-042"], ["OPUS-043", "OPUS-031"], ["OPUS-043", "ANC-HESSE"], ["OPUS-043", "ANC-BURNHAM"], ["OPUS-043", "ANC-LEE-UFAN"], ["INQ-29", "ANC-HESSE"], ["INQ-29", "ANC-BURNHAM"], ["INQ-29", "OPUS-031"],
        ["OPUS-044", "INQ-30"], ["OPUS-044", "OPUS-043"], ["OPUS-044", "OPUS-040"], ["OPUS-044", "ANC-KITAEV"], ["OPUS-044", "ANC-XENAKIS"], ["OPUS-044", "ANC-TINGUELY"], ["INQ-30", "ANC-KITAEV"], ["INQ-30", "ANC-XENAKIS"]
      ]
    };

const OPUS_TO_CHAMBER = {
      "OPUS-044": "syk",
      "opus_044": "syk",
      "OPUS-043": "fuzzball",
      "opus_043": "fuzzball",
      "OPUS-042": "amplituhedron",
      "OPUS-041": "happyqec",
      "OPUS-040": "erepr",
      "OPUS-039": "wheelergeon",
      "OPUS-038": "causalfoam",
      "OPUS-037": "moyalfoam",
      "OPUS-036": "spinnetwork",
      "OPUS-035": "holographic",
      "OPUS-034": "crossover",
      "OPUS-033": "recurrence",
      "OPUS-032": "nucleation",
      "OPUS-031": "pagehorizon",
      "OPUS-030": "silica",
      "OPUS-029": "causal",
      "OPUS-028": "relic",
      "OPUS-020": "cryostat",
      "OPUS-019": "borehole",
      "OPUS-018": "drift",
      "OPUS-017": "desiccation",
      "OPUS-014": "lithic",
      "OPUS-006": "attractors",
      "OPUS-003": "chamber"
    };
