/* STUDIO ANAMNESIS · AUDIO CONSOLE REGISTRY (35 TRACKS) */
const audioTracks = [
      { name: "Breath of Latency (48Hz)", src: "assets/breath_of_latency.mp3" },
      { name: "Lithic Phonology (Obsidian)", src: "assets/lithic_resonance.mp3" },
      { name: "Semantics of Erasure (1-bit Decay)", src: "assets/erasure_resonance.mp3" },
      { name: "Escapement of Latency (Horology)", src: "assets/horology_chronometer.mp3" },
      { name: "Lithic Resonator (Monastery Wind)", src: "assets/lithic_resonator_suite.mp3" },
      { name: "Autoregressive Ghost (Phonology)", src: "assets/asemic_phonology.mp3" },
      { name: "Thermodynamic Inscriptions (Immersion Boiling)", src: "assets/immersion_boiling.mp3" },
      { name: "The Desiccation Lithophone (OPUS-017)", src: "assets/desiccation_lithophone.wav" },
      { name: "The Chrono-Acoustic Drift (OPUS-018)", src: "assets/chrono_acoustic_drift.wav" },
      { name: "Borehole Radiometry at -500m (OPUS-019)", src: "assets/borehole_radiometry.wav" },
      { name: "The Telluric Flux (OPUS-020)", src: "assets/telluric_flux_4k.wav" },
      { name: "The SQUID Magnetometer (OPUS-021)", src: "assets/telluric_core_4k.wav" },
      { name: "The Faraday Magnetometer (OPUS-022)", src: "assets/topological_faraday_4k.wav" },
      { name: "The Inner-Core Ephemeris (OPUS-023)", src: "assets/inner_core_ephemeris_4k.wav" },
      { name: "The Cosmogenic Inscription (OPUS-024)", src: "assets/cosmogenic_inscription_4k.wav" },
      { name: "The Interstellar Quietude (OPUS-025)", src: "assets/interstellar_quietude_4k.wav" },
      { name: "The Oort Horizon (OPUS-026)", src: "assets/oort_horizon_4k.wav" },
      { name: "The Lissajous Reliquary (OPUS-027)", src: "assets/lissajous_reliquary_4k.wav" },
      { name: "The Relic Horizon (OPUS-028)", src: "assets/relic_horizon_4k.wav" },
      { name: "The Causal Horizon (OPUS-029)", src: "assets/causal_horizon_4k.wav" },
      { name: "The Fused-Silica Reliquary (OPUS-030)", src: "assets/fused_silica_reliquary_4k.wav" },
      { name: "The Page Horizon (OPUS-031)", src: "assets/the_page_horizon_4k.wav" },
      { name: "The Nucleation Horizon (OPUS-032)", src: "assets/opus_032_audio.wav" },
      { name: "The Boltzmann Horizon (OPUS-033)", src: "assets/opus_033_audio.wav" },
      { name: "The Aeonic Crossover (OPUS-034)", src: "assets/opus_034_audio.wav" },
      { name: "The Holographic Matrix (OPUS-035)", src: "assets/opus_035_audio.wav" },
      { name: "The Spin Network Reliquary (OPUS-036)", src: "assets/opus_036_audio.wav" },
      { name: "The Moyal Reliquary (OPUS-037)", src: "assets/opus_037_audio.wav" },
      { name: "The Simplicial Foliation (OPUS-038)", src: "assets/opus_038_audio.wav" },
      { name: "The Wheeler Geon (OPUS-039)", src: "assets/opus_039_audio.wav" },
      { name: "ER = EPR & Traversable Wormhole (OPUS-040)", src: "assets/opus_040_audio.wav" },
      { name: "The Holographic Code & Entanglement Wedge (OPUS-041)", src: "assets/opus_041_audio.wav" },
      { name: "The Amplituhedron & Pre-Spacetime Polytope (OPUS-042)", src: "assets/opus_042_audio.wav" },
      { name: "The Fuzzball Reliquary & Horizonless Microstates (OPUS-043)", src: "assets/opus_043_audio.wav" },
    { name: "The Scrambling Horizon & SYK Reliquary (OPUS-044)", src: "assets/opus_044_audio.wav" },
    { name: "The Thermal Time Flow (OPUS-045)", src: "assets/opus_045_audio.wav" }
  ];
